import type { RuleDsl } from "./dsl.js";

export type ExportFormat = "json" | "yaml" | "python" | "dsl";

export function compileDslToJson(dsl: RuleDsl): string {
  return JSON.stringify(dsl, null, 2);
}

export function compileDslToYaml(dsl: RuleDsl): string {
  const lines: string[] = [
    `name: "${dsl.metadata.name}"`,
    `version: ${dsl.metadata.version}`,
  ];
  if (dsl.metadata.description) {
    lines.push(`description: "${dsl.metadata.description}"`);
  }
  lines.push("blocks:");
  for (const block of dsl.blocks) {
    lines.push(`  - type: ${block.type}`);
    if (block.logic) lines.push(`    logic: ${block.logic}`);
    if (block.outcome) lines.push(`    outcome: ${block.outcome}`);
    if (block.conditions) {
      lines.push("    conditions:");
      for (const c of block.conditions) {
        lines.push(`      - field: ${c.field}`);
        lines.push(`        operator: "${c.operator}"`);
        lines.push(`        value: ${JSON.stringify(c.value)}`);
      }
    }
    if (block.evidence) {
      lines.push(`    evidence: [${block.evidence.map((e) => `"${e}"`).join(", ")}]`);
    }
  }
  return lines.join("\n");
}

export function compileDslToPython(dsl: RuleDsl): string {
  const fnName = dsl.metadata.name
    .replace(/[^a-zA-Z0-9]/g, "_")
    .replace(/^(\d)/, "_$1")
    .toLowerCase();

  const lines = [
    '"""',
    `Policy Brain exported rule: ${dsl.metadata.name}`,
    `Version: ${dsl.metadata.version}`,
    'Generated by Policy Brain — AI proposes, humans approve.',
    '"""',
    "from typing import Any",
    "",
    `def ${fnName}(claim: dict[str, Any]) -> dict[str, Any]:`,
    '    """Evaluate claim against exported policy rule."""',
    "    trace: list[str] = []",
  ];

  for (const block of dsl.blocks) {
    if (block.type === "condition" && block.conditions) {
      const parts = block.conditions.map((c) => {
        const field = `claim.get("${c.field}")`;
        const op = c.operator;
        const val = JSON.stringify(c.value);
        if (op === ">=") return `(${field} is not None and ${field} >= ${val})`;
        if (op === "<=") return `(${field} is not None and ${field} <= ${val})`;
        if (op === "in") return `(${field} in ${val})`;
        if (op === "exists") return `({field} is not None)`;
        if (op === "==") return `({field} == ${val})`;
        return `(${field} {op} {val})`;
      });
      const joiner = block.logic === "OR" ? " or " : " and ";
      lines.push(`    if ${parts.join(joiner)}:`);
      lines.push(`        trace.append("condition:${block.type}")`);
    }
    if (block.type === "decision" && block.outcome) {
      lines.push(`        return {"decision": "${block.outcome}", "trace": trace}`);
    }
  }

  lines.push('    return {"decision": "DENY", "trace": trace}');
  return lines.join("\n");
}

export function compileDsl(dsl: RuleDsl, format: ExportFormat): string {
  switch (format) {
    case "json":
      return compileDslToJson(dsl);
    case "yaml":
      return compileDslToYaml(dsl);
    case "python":
      return compileDslToPython(dsl);
    case "dsl":
      return compileDslToJson(dsl);
  }
}
